import Header from './components/Header';
import Footer from './components/Footer';
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "sarkarinaukri-india.in",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white">
        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="flex-grow container mx-auto p-4">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
